### ISSUE TITLE
2.0.1 still has a.createparser is not a function issue

### ISSUE THREAD

**Issue by comebacktomorrow** [bitfocus/companion-module-tslproducts-umdlistener#2]
I commented on the old issue, but I wasn't sure if that would be seen. I just upgraded to 3.1.0+6080 beta with 2.0.1 of the listener to try and deal with this issue - I'm sad to say that the issue still exists. Also tried it in a new install of +6090 and it exhibited the same behaviour.

**Comment by comebacktomorrow** [comment]
As a further note, tried it again running latest beta = same behaviour. I pulled this package and set up companion to run the module as dev mode = it works fine.

**Comment by josephdadams** [comment]
Yes it’s because the yarn lock file included references the wrong version of packet where they removed that function. Needs to be 0.0.6. I just haven’t had time to push the fix

**Comment by josephdadams** [comment]
please try `v2.0.2` of the module. thanks.

**Comment by comebacktomorrow** [comment]
Thanks Joseph, I'm sad to say the problem still exists with 3.1.0+6107 running 2.0.2 - I wish I could be more help!

**Comment by josephdadams** [comment]
Oh well I tried

**Comment by comebacktomorrow** [comment]
Thanks anyway!
